# Generated by Django 5.2.7 on 2026-07-16 15:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='assuré')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='téléphone')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='identifiant client')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent')], default='agent', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='catégorie')),
                ('policy_number', models.CharField(db_index=True, max_length=100, verbose_name='police')),
                ('agent_reference', models.CharField(blank=True, max_length=100)),
                ('agent_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='événement')),
                ('pack_code', models.CharField(blank=True, max_length=100)),
                ('registration', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='immatriculation')),
                ('net_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='prime TTC')),
                ('net_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('receipt', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='quittance')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='date d’effet')),
                ('end_date', models.DateField(db_index=True, verbose_name='date de fin')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='date d’émission')),
                ('renewal_status', models.CharField(choices=[('to_contact', 'À contacter'), ('to_confirm', 'À confirmer'), ('wants', 'Souhaite renouveler'), ('quote', 'Devis demandé'), ('callback', 'Rappel demandé'), ('renewed', 'Renouvelé'), ('refused', 'Ne souhaite pas renouveler'), ('competitor', 'Parti chez un concurrent'), ('terminated', 'Résilié'), ('unreachable', 'Injoignable')], db_index=True, default='to_contact', max_length=20)),
                ('manually_terminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='renewals.client')),
                ('renewed_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_contract', to='renewals.contract')),
            ],
            options={
                'ordering': ['end_date', 'client__name'],
            },
        ),
        migrations.CreateModel(
            name='CallInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('phone', 'Téléphone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'Visite')], default='phone', max_length=12)),
                ('call_result', models.CharField(choices=[('not_called', 'Pas encore appelé'), ('answered', 'A répondu'), ('voicemail', 'Boîte vocale'), ('unreachable', 'Injoignable'), ('off', 'Téléphone éteint'), ('wrong', 'Numéro incorrect'), ('busy', 'Occupé'), ('callback', 'Rappel demandé')], max_length=20)),
                ('renewal_status', models.CharField(choices=[('to_contact', 'À contacter'), ('to_confirm', 'À confirmer'), ('wants', 'Souhaite renouveler'), ('quote', 'Devis demandé'), ('callback', 'Rappel demandé'), ('renewed', 'Renouvelé'), ('refused', 'Ne souhaite pas renouveler'), ('competitor', 'Parti chez un concurrent'), ('terminated', 'Résilié'), ('unreachable', 'Injoignable')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('next_follow_up', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='renewals.contract')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('added_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_renewals', to='renewals.contract')),
                ('old_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_record', to='renewals.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='renewals.contract')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('policy_number', 'receipt'), name='unique_policy_receipt'),
        ),
    ]
