# Generated by Django 5.2.7 on 2026-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0007_clear_contracts_and_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_provisional',
            field=models.BooleanField(db_index=True, default=False, verbose_name='suivi provisoire actif'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_allowed_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='provisoires autorisées'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_attestation',
            field=models.CharField(blank=True, max_length=100, verbose_name='attestation provisoire'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_delivered_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='provisoires délivrées'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance provisoire'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='état du suivi provisoire'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('upcoming', 'Échéances à venir'), ('bordereau', 'Bordereau de production'), ('provisional', 'Suivi des provisoires'), ('contacts', 'Mise à jour des contacts'), ('general', 'Fichier Excel standard')], default='general', max_length=20, verbose_name='type d’import'),
        ),
    ]
