# Generated by Django 5.2.7 on 2026-07-28 11:45

import re
import unicodedata
from datetime import timedelta

from django.db import migrations, models


def normalized_registration(value):
    value = (
        unicodedata.normalize("NFKD", str(value or ""))
        .encode("ascii", "ignore")
        .decode()
        .lower()
    )
    return re.sub(r"[^a-z0-9]+", "", value)


def link_vehicle_renewals(apps, schema_editor):
    Contract = apps.get_model("renewals", "Contract")
    contracts = list(
        Contract.objects.exclude(registration="").only(
            "pk",
            "registration",
            "effective_date",
            "issue_date",
            "end_date",
            "renewal_status",
            "renewed_contract_id",
            "manually_terminated",
        )
    )
    groups = {}
    for contract in contracts:
        registration = normalized_registration(contract.registration)
        if registration:
            groups.setdefault(registration, []).append(contract)

    claimed_successors = {
        contract.renewed_contract_id: contract.pk
        for contract in contracts
        if contract.renewed_contract_id
    }
    changed = []
    for vehicle_contracts in groups.values():
        for old_contract in sorted(
            vehicle_contracts,
            key=lambda contract: (contract.end_date, contract.pk),
        ):
            if (
                old_contract.manually_terminated
                or old_contract.renewal_status == "terminated"
            ):
                continue
            earliest_start = old_contract.end_date - timedelta(days=1)
            successors = []
            for candidate in vehicle_contracts:
                candidate_start = candidate.effective_date or candidate.issue_date
                if (
                    candidate.pk != old_contract.pk
                    and candidate_start
                    and candidate_start >= earliest_start
                    and candidate.end_date > old_contract.end_date
                    and not candidate.manually_terminated
                    and candidate.renewal_status != "terminated"
                    and claimed_successors.get(candidate.pk)
                    in (None, old_contract.pk)
                ):
                    successors.append(
                        (candidate_start, candidate.end_date, candidate.pk, candidate)
                    )
            if not successors:
                continue
            successor = min(successors, key=lambda item: item[:3])[3]
            if (
                old_contract.renewed_contract_id != successor.pk
                or old_contract.renewal_status != "renewed"
            ):
                if (
                    old_contract.renewed_contract_id
                    and claimed_successors.get(old_contract.renewed_contract_id)
                    == old_contract.pk
                ):
                    claimed_successors.pop(old_contract.renewed_contract_id)
                old_contract.renewed_contract_id = successor.pk
                old_contract.renewal_status = "renewed"
                claimed_successors[successor.pk] = old_contract.pk
                changed.append(old_contract)

    if changed:
        Contract.objects.bulk_update(
            changed,
            ["renewed_contract", "renewal_status"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0007_clear_contracts_and_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_provisional',
            field=models.BooleanField(db_index=True, default=False, verbose_name='suivi provisoire actif'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_allowed_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='provisoires autorisées'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_attestation',
            field=models.CharField(blank=True, max_length=100, verbose_name='attestation provisoire'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_delivered_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='provisoires délivrées'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance provisoire'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provisional_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='état du suivi provisoire'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('upcoming', 'Échéances à venir'), ('bordereau', 'Bordereau de production'), ('provisional', 'Suivi des provisoires'), ('contacts', 'Mise à jour des contacts'), ('general', 'Fichier Excel standard')], default='general', max_length=20, verbose_name='type d’import'),
        ),
        migrations.RunPython(
            link_vehicle_renewals,
            migrations.RunPython.noop,
        ),
    ]
