# Generated by Django 5.2.7 on 2026-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0008_contract_is_provisional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='provisional_selected_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 signifie que le maximum autorisé est retenu tant que le client n’a pas fait un autre choix.', verbose_name='provisoires choisies'),
        ),
    ]
